spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/login_service
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: YOUR_PASSWORD_HERE
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
